spring:
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                naming:
                    physical-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        open-in-view: false
    datasource:
        url: jdbc:mysql://172.17.0.2:3306/BOOKQUEST
        username: root
        password: helloworld
        driver-class-name: com.mysql.cj.jdbc.Driver

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE